### PR TITLE
Add driver for Adesto AT45DB family

### PR DESCRIPTION
**Pull request by marcuschangarm**
@geky 

Can you review this code for me, please?

Also, do you want it inside this library or should we create a new repository for it?

### CODE REVIEW

**Comment by geky** [comment]
It looks good 👍, although yes we want this in a seperate repository.

Although looking at this closer, it looks like the AT45DB is a DataFlash device. Does this driver actually cover (or could cover) all DataFlash devices?

I'm thinking we should name this class DataFlashBlockDevice and put it in its own dataflash-driver repo, thoughts?

Also ccing @chrissnow, since this fits into the same space as his [DataFlashDevice](https://github.com/chrissnow/DataFlashDevice). Not sure how to resolve the duplication, I think we may go with @marcuschangarm's implementation since we've already been testing it.

**Comment by marcuschangarm** [comment]
You can get DataFlash devices that don't use normal SPI, so I wouldn't call it a DataFlash driver. It should cover the AT45DB family.

The biggest difference between my driver and @chrissnow 's is that his uses the flash page size directly (binary and non-binary sizes) while mine reconfigures the device to use binary sizes if necessary. I suspect that non-binary sizes might give us problems further up the chain.

**Comment by chrissnow** [comment]
@marcuschangarm the page sizes being non binary has been fine since the max block size was increased by @geky.

I've been running my version on a couple of hundred devices without issues, I wouldn't say it's fully tested though!

Bear in mind re configuring the block size wipes the device. that won't be great for anyone already using the chip....

**Comment by marcuschangarm** [comment]
Ah, ok. 

I've updated the driver to handle non-binary addresses. If people want to reconfigure the device, they have to set a compile flag.

**Comment by geky** [comment]
The config option was a good compromise.

I'm going to go ahead and move forward with the name DataFlash. Other technologies such as SPIFBlockDevice will have to solve the different protocols issue when users want to adopt QSPI as well.

Also by using the name DataFlashBlockDevice, it shouldn't conflict with @chrissnow's DataFlashDevice class if they end up in the same codebase.

I've moved the driver over here:
https://github.com/armmbed/dataflash-driver

Feel free to raise any issues/prs for things that could be improved over there.

**Pull request closed without merging**
